/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package main;

import animation.AnimationClip;
import animation.ClipPlayer;
import animation.Polygon;
import animation.PoseMorpher;
import animation.World;
import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.function.DoubleConsumer;
import skeleton.Body;
import skeleton.Bone;
import skeleton.Skin;
import skeleton.Tip;
import skeleton.attachables.Anchor;
import skeleton.attachables.Motor;
import utils.TupleD;
import viewer.Viewer;

/**
 *
 * @author rlaka
 */
public class Main {

    public static Viewer viewer;

    // once LoadPose has been used, Reset restores THIS pose instead of the
    // default build pose -- null means "no pose loaded yet, use the default".
    private static File currentPoseFile;

    private static final double DRAG_KICK_SCALE = 6.0; // velocity gained per unit dragged

    // the playable figure: its poses, walk clip, skin and named tips ('h'
    // switches). Its _L/_R poses are horizontally-mirrored pairs (mirrored
    // around bone[0]/tip0); which one loads is picked by jumpDirectionSign.
    private static CharacterProfile profile = CharacterProfile.HUMAN;

    // JUMP sequence constants -- see onJump/onStep wiring below.
    private static final double JUMP_START_X = 4.5; // near the viewer's right edge; this
                                                      // charging pose leans left from the
                                                      // hip, so the hip itself is the body's
                                                      // rightmost point
    private static final double JUMP_CHARGE_SECONDS = 1.0; // for the JUMP button, a fixed
            // hold duration; for a keypress jump, the hold time (up to this cap) that
            // maps the charge fraction below to 0..1
    private static final double JUMP_MORPH_SECONDS = 0.25; // standing->charging and charging->flying
    private static final double JUMP_RECOVERY_MORPH_SECONDS = 0.25; // ragdoll->standing recovery
    private static final double JUMP_LAUNCH_ANGLE_DEG = 55.0; // JUMP button only (fixed timing)
    private static final double JUMP_LAUNCH_SPEED = 10.1; // JUMP button only (fixed timing) --
            // needs enough range to reach the center-left wall obstacle while still airborne

    // keypress jump aiming: the longer 'o'/'p' is held (up to JUMP_CHARGE_SECONDS,
    // after which it's cropped), the faster and steeper the launch -- linearly
    // interpolated by the charge fraction computed in onStep's jumpCharging branch.
    private static final double JUMP_LAUNCH_SPEED_MIN = 1.0;
    private static final double JUMP_LAUNCH_SPEED_MAX = 12.0;
    private static final double JUMP_LAUNCH_ANGLE_MIN_DEG = 30.0;
    private static final double JUMP_LAUNCH_ANGLE_MAX_DEG = 60.0;

    // charge-meter: a horizontal bar below the figure (not a fixed world
    // height, so it stays put under the figure even standing on a raised
    // rock) showing the current charge fraction while a keypress jump is held.
    private static final double CHARGE_METER_GAP_BELOW_FIGURE = 0.2;
    private static final double CHARGE_METER_WIDTH = 2.0;
    private static final double CHARGE_METER_HEIGHT = 0.15;
    private static final double JUMP_RAGDOLL_DELAY_SECONDS = 1.0; // how long after the
            // FIRST post-launch collision the figure keeps hanging on its landed
            // anchors before they're all released, letting it fall/ragdoll freely
    private static final double JUMP_RECOVER_DELAY_SECONDS = 0.5; // how long after the
            // NEXT collision (the fall after the anchor release above) the figure
            // keeps ragdolling before morphing back to the profile's standing pose

    // keyboard walking ('u' left / 'i' right, held): the profile's walk-left
    // clip (generated by editor.WalkCycleGenerator / HorseGenerator) and its
    // mirror image, played kinematically by ClipPlayer, which follows the
    // terrain (slopes, steps up/down to ClipPlayer.MAX_STEP_UP/DOWN). On
    // release, or when the way is blocked, it morphs back to the standing
    // pose over WALK_STOP_MORPH_SECONDS and physics takes over again;
    // stepping off a bigger drop hands over to physics mid-stride instead
    // (it falls).
    private static final double WALK_STOP_MORPH_SECONDS = 0.25;
    private static final double WALK_OFF_PUSH_SPEED = 1.5; // upward push when stepping off a drop
    private static final double LEVEL_GROUND_TOLERANCE = 0.05; // feet this close in height stand level
    private static final double CLEAR_SPOT_SEARCH = 2.0; // how far sideways to look for room to stand up
    private static final double CLEAR_SPOT_STEP = 0.1;
    private static final double WALK_GROUND_TOLERANCE = 0.02; // how far below a touching-down foot
            // still counts as "something to stand on"
    private static final int RAGDOLL_RELEASE_SUPPRESSION_FRAMES = 12; // ~0.2s: briefly
            // keep auto-landing suppressed right after releasing the anchors, so the
            // same still-touching tip doesn't get re-pinned before it's actually had
            // a chance to fall away -- otherwise the "next collision" below would
            // fire immediately, on the very same spot, instead of after a real fall.

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws IOException {
        viewer = new Viewer();
        viewer.loadBackgroundImage("src/assets/jungle2.png");

        Body body = new Body();
        applySkin(body);
        World world = new World(body);
        world.obstacles.add(Polygon.load("src/assets/Rock_01.json", new TupleD(-4.0, 0.0)));
        world.obstacles.add(Polygon.load("src/assets/Rock_02.json", new TupleD(6.5, 0.0)));
        // Rock_01's own flat "back" edge sits exactly at its own placement x
        // (local x=0); Rock_02's sits at its placement x + 4.1 (its local
        // x-max, ~410px at its 100px/unit scale). A mirrored Rock_01 placed
        // at Rock_01's own back-x extends further left instead of right, so
        // the two backs coincide with fronts facing apart -- back to back.
        // An unmirrored Rock_01 placed at Rock_02's back-x does the same
        // thing the other way around: its own (unmirrored) back coincides
        // with Rock_02's back, extending further right.
        world.obstacles.add(Polygon.load("src/assets/Rock_01.json", new TupleD(-4.0, 0.0), true));
        world.obstacles.add(Polygon.load("src/assets/Rock_01.json", new TupleD(6.5 + 4.1, 0.0)));
        resetBody(body, world);

        PoseMorpher poseMorpher = new PoseMorpher();
        // set by onLoadTarget below; declared here so onStep can reach it once
        // a morph completes.
        Body[] targetPose = new Body[1];

        // JUMP sequence state -- see onJump below. jumpCharging counts real
        // playback seconds through the "play physics for 1s" phase;
        // jumpPendingLaunch marks that the morph currently in progress is
        // JUMP's own (to flying pose), so its completion should launch
        // straight into flight instead of pausing like a manual Morph does.
        boolean[] jumpCharging = {false};
        double[] jumpChargeElapsed = {0.0};
        boolean[] jumpPendingLaunch = {false};

        // keypress-triggered jump ('o'/'p'): unlike the JUMP button (which
        // teleports to JUMP_START_X and always launches left), this starts
        // from wherever the figure currently stands -- jumpPendingChargeStart
        // marks that the in-progress morph is standing->charging IN PLACE,
        // so its completion should start the ordinary jumpCharging hold
        // instead of anything else a morph-completion could mean. Once
        // launch actually happens, jumpDirectionSign picks which way (-1
        // left, +1 right); the JUMP button sets it to -1 to keep its own
        // existing always-left behavior.
        boolean[] jumpPendingChargeStart = {false};
        double[] jumpDirectionSign = {-1.0};

        // per-jump aiming: jumpIsKeyDriven distinguishes a keypress jump
        // (release-triggered, speed/angle scaled by hold duration) from the
        // JUMP button (fixed 1s hold, fixed speed/angle) inside the SAME
        // shared jumpCharging/launch logic below. jumpKeyHeld tracks whether
        // the key that started the current charge is still down; releasing
        // it is what ends the hold. jumpLaunchSpeed/jumpLaunchAngleDeg are
        // computed once, at the moment charging ends, and used at the actual
        // launch (which only happens later, once the flying-morph completes).
        boolean[] jumpIsKeyDriven = {false};
        boolean[] jumpKeyHeld = {false};
        double[] jumpLaunchSpeed = {0.0};
        double[] jumpLaunchAngleDeg = {0.0};

        // post-launch ragdoll/recover sequence, four phases in order:
        //  1. awaitingCollision: true from the moment of launch until the figure
        //     first lands on something (body.anchors going from empty to non-empty,
        //     via World.pinLandedTips). At that instant every motor except the neck
        //     is disabled -- once part of the body is pinned (e.g. a hand+elbow
        //     grabbing the wall), a motor whose far tip is now pinned can no longer
        //     move that side, so its whole reaction torque lands one-sided on
        //     whatever's still hanging free, swinging it like a pendulum instead of
        //     holding a pose that no longer matches reality. Then collisionTimerRunning
        //     counts up for JUMP_RAGDOLL_DELAY_SECONDS.
        //  2. at that timer's end, every anchor is released (body.launch with a zero
        //     kick) and auto-landing is suppressed for RAGDOLL_RELEASE_SUPPRESSION_FRAMES
        //     (landingSuppressionFramesLeft) so the same still-touching tip doesn't
        //     just get re-pinned next frame -- it needs to actually fall away first.
        //  3. once that brief suppression ends, awaitingSecondCollision waits for the
        //     figure to land again (a genuine second collision, after really falling),
        //     then secondCollisionTimerRunning counts up for JUMP_RECOVER_DELAY_SECONDS.
        //  4. at THAT timer's end, a morph back to the profile's standing pose (facing
        //     the way it jumped) starts, the profile's fixpoint tip held in place (the
        //     human's left foot) -- jumpPendingStandRecovery
        //     marks that motors should be re-enabled once that morph completes.
        boolean[] awaitingCollision = {false};
        boolean[] collisionTimerRunning = {false};
        double[] secondsSinceCollision = {0.0};
        int[] landingSuppressionFramesLeft = {0};
        boolean[] awaitingSecondCollision = {false};
        boolean[] secondCollisionTimerRunning = {false};
        double[] secondsSinceSecondCollision = {0.0};
        boolean[] jumpPendingStandRecovery = {false};

        // walking: walker plays the clip while active (instead of physics,
        // like a morph); walkPendingStop marks that the morph in progress is
        // the walk's own ending, so its completion resumes physics instead
        // of pausing like a manual Morph does.
        // walkClips = {walk left, walk right}: reloaded when the figure changes.
        AnimationClip[] walkClips = loadWalkClips();
        ClipPlayer walker = new ClipPlayer(world);
        boolean[] walkPendingStop = {false};
        // which way the figure last went (walk or jump) -- a figure seen
        // side-on (the horse) has to end up standing that way round.
        double[] facingSign = {-1.0};
        Runnable stopWalk = () -> {
            if (!walker.isActive()) {
                return;
            }
            double groundY = walker.stanceTip(body).position.second;
            walker.stop();
            // the standing pose is for level ground: stopped with its feet on
            // different levels (e.g. forelegs already up a step), it just
            // holds the walk pose it's in instead -- the motors keep it, and
            // physics pins whatever is on the ground. Morphing into the flat
            // pose there would push the upper feet into the step.
            if (!groundIsLevelUnder(world, body)) {
                return;
            }
            Body standing = loadPose(profile.standingPathFor(facingSign[0]));
            // the human's standing pose has its left foot on the -x side;
            // mid-stride the left foot is just as often the one on the +x
            // side, and pivoting into the unmirrored pose would then swing a
            // leg through and hop the whole figure about half a stride. So
            // end in whichever version matches the feet as they are.
            if (!profile.sideView
                    && body.tipByName.get(profile.feetTips[0]).position.first
                    > body.tipByName.get(profile.feetTips[1]).position.first) {
                mirrorPose(standing);
            }
            targetPose[0] = standing;
            walkPendingStop[0] = true;
            // pivot on the hip, not a foot: it stays where the walk left it
            // (just settling to standing height above the stance foot's
            // ground), and the feet gather under it -- pivoting on a foot
            // would lunge the whole body forward or back by up to a step.
            double lowestStandingFoot = Double.POSITIVE_INFINITY;
            for (String foot : profile.feetTips) {
                lowestStandingFoot = Math.min(lowestStandingFoot, standing.tipByName.get(foot).position.second);
            }
            double standingHipHeight = standing.bone[0].tips[0].position.second - lowestStandingFoot;
            Tip hipTip = body.bone[0].tips[0];
            poseMorpher.setTarget(standing, WALK_STOP_MORPH_SECONDS,
                    new TupleD(hipTip.position.first, groundY + standingHipHeight), hipTip);
        };

        viewer.onStep = () -> {
            if (poseMorpher.isActive()) {
                poseMorpher.morphStep(body);
                if (!poseMorpher.isActive()) {
                    // this tick just reached the target pose -- replace
                    // whatever anchors AND physical upgrades were active
                    // before/during the morph with the target's own, so
                    // whatever runs next (physics, or a launch) honors
                    // exactly what the target pose intended -- e.g. a
                    // different jitter amplitude -- not a leftover mix of both.
                    if (targetPose[0] != null) {
                        for (Anchor a : new ArrayList<>(body.anchors)) {
                            body.removeAnchor(a.tipsSnapshot()[0].name);
                        }
                        for (Anchor a : targetPose[0].anchors) {
                            body.addAnchor(a.tipsSnapshot()[0].name, a.angleEnabled);
                        }
                        body.applyPhysicalUpgradesFrom(targetPose[0]);
                    }
                    boolean standRecoveryJustCompleted = jumpPendingStandRecovery[0];
                    if (standRecoveryJustCompleted) {
                        // reached the standing pose -- motors can safely hold
                        // it again now that nothing is still half-pinned.
                        jumpPendingStandRecovery[0] = false;
                        for (Motor m : body.motors) {
                            m.enabled = true;
                        }
                    }
                    boolean walkStopJustCompleted = walkPendingStop[0];
                    walkPendingStop[0] = false;
                    boolean chargeJustStarted = jumpPendingChargeStart[0];
                    if (chargeJustStarted) {
                        // reached the charging pose (morphed in place from
                        // wherever the figure was standing) -- start the same
                        // "hold the crouch under physics" phase the JUMP
                        // button starts immediately after loading Charging.json.
                        jumpPendingChargeStart[0] = false;
                        jumpChargeElapsed[0] = 0.0;
                        jumpCharging[0] = true;
                    }
                    if (jumpPendingLaunch[0]) {
                        // kick: drop every anchor (including the ones just
                        // reattached above) and launch, then keep playing --
                        // unlike a manual Morph, JUMP doesn't pause here.
                        // jumpLaunchSpeed/jumpLaunchAngleDeg were already
                        // decided back when charging ended (fixed values for
                        // the JUMP button, hold-duration-scaled for a keypress).
                        jumpPendingLaunch[0] = false;
                        double rad = Math.toRadians(jumpLaunchAngleDeg[0]);
                        body.launch(new TupleD(jumpDirectionSign[0] * jumpLaunchSpeed[0] * Math.cos(rad), jumpLaunchSpeed[0] * Math.sin(rad)));
                        awaitingCollision[0] = true;
                        collisionTimerRunning[0] = false;
                    } else if (!chargeJustStarted && !standRecoveryJustCompleted && !walkStopJustCompleted) {
                        viewer.stopPlaying();
                    }
                }
            } else if (walker.isActive()) {
                ClipPlayer.Status walkStatus = walker.step(body);
                if (walkStatus == ClipPlayer.Status.STEPPED_INTO_AIR) {
                    // stepped off an edge: let go mid-stride and let physics
                    // drop it (motors keep holding the walk pose), then join
                    // the jump's own land -> recover-to-standing sequence at
                    // its "fall after release" phase -- rather than morphing
                    // to standing in mid-air, whose wider stance can push the
                    // rear foot into the very slope it just walked off.
                    // carry the walking momentum over the edge, plus the rear
                    // leg's push-off -- a little hop down (uniform kick, so it
                    // doesn't distort the pose). Without that the rear foot,
                    // still on the ledge, gets pinned there before the body has
                    // dropped past the edge, ending in a split.
                    TupleD momentum = walker.hipVelocity();
                    walker.stop();
                    // no balancing mid-air (like the jump's flying pose): the
                    // human's HipBalancer would swing the rear leg back onto the
                    // ledge. The recovery to standing restores the pose's own.
                    body.physicalUpgrades.clear();
                    body.launch(new TupleD(momentum.first, Math.max(0.0, momentum.second) + WALK_OFF_PUSH_SPEED));
                    world.suppressAutoLanding = true;
                    landingSuppressionFramesLeft[0] = RAGDOLL_RELEASE_SUPPRESSION_FRAMES;
                } else if (walkStatus == ClipPlayer.Status.BLOCKED) {
                    stopWalk.run();
                }
            } else {
                world.step();
                if (jumpCharging[0]) {
                    jumpChargeElapsed[0] += 1.0 / 60.0;
                    // a keypress jump ends its hold on key release; the JUMP
                    // button (fixed timing) still ends after JUMP_CHARGE_SECONDS.
                    boolean chargeDone = jumpIsKeyDriven[0]
                            ? !jumpKeyHeld[0]
                            : jumpChargeElapsed[0] >= JUMP_CHARGE_SECONDS;
                    if (chargeDone) {
                        jumpCharging[0] = false;
                        jumpPendingLaunch[0] = true;
                        if (jumpIsKeyDriven[0]) {
                            double fraction = Math.max(0.0, Math.min(1.0, jumpChargeElapsed[0] / JUMP_CHARGE_SECONDS));
                            jumpLaunchSpeed[0] = JUMP_LAUNCH_SPEED_MIN + fraction * (JUMP_LAUNCH_SPEED_MAX - JUMP_LAUNCH_SPEED_MIN);
                            jumpLaunchAngleDeg[0] = JUMP_LAUNCH_ANGLE_MIN_DEG + fraction * (JUMP_LAUNCH_ANGLE_MAX_DEG - JUMP_LAUNCH_ANGLE_MIN_DEG);
                        } else {
                            jumpLaunchSpeed[0] = JUMP_LAUNCH_SPEED;
                            jumpLaunchAngleDeg[0] = JUMP_LAUNCH_ANGLE_DEG;
                        }
                        Body flying = loadPose(profile.flyingPathFor(jumpDirectionSign[0]));
                        targetPose[0] = flying;
                        // pivot on what pushes off, raised if any part of the
                        // flying pose would reach below it -- the morph is
                        // kinematic, and launching with a limb sunk into the
                        // ground would kick the whole figure into a spin
                        Tip takeoffTip = body.tipByName.get(profile.takeoffTip);
                        double lowest = Double.POSITIVE_INFINITY;
                        for (Tip t : flying.tipByName.values()) {
                            lowest = Math.min(lowest, t.position.second);
                        }
                        double raise = Math.max(0.0, flying.tipByName.get(profile.takeoffTip).position.second - lowest);
                        poseMorpher.setTarget(flying, JUMP_MORPH_SECONDS,
                                takeoffTip.position.add(new TupleD(0.0, raise)), takeoffTip);
                    }
                }
                if (awaitingCollision[0] && !body.anchors.isEmpty()) {
                    // first post-launch collision: World.pinLandedTips() just
                    // anchored something -- disable every motor (see the state
                    // declaration above for why) EXCEPT the neck, which is left
                    // on so the head keeps actively holding/orienting itself
                    // instead of also going limp, and start the
                    // recover-to-standing countdown.
                    awaitingCollision[0] = false;
                    collisionTimerRunning[0] = true;
                    secondsSinceCollision[0] = 0.0;
                    for (Motor m : body.motors) {
                        if (!"neck".equals(m.name)) {
                            m.enabled = false;
                        }
                    }
                } else if (collisionTimerRunning[0]) {
                    secondsSinceCollision[0] += 1.0 / 60.0;
                    if (secondsSinceCollision[0] >= JUMP_RAGDOLL_DELAY_SECONDS) {
                        collisionTimerRunning[0] = false;
                        world.suppressAutoLanding = true;
                        body.launch(new TupleD(0.0, 0.0)); // drops every anchor, zero kick
                        landingSuppressionFramesLeft[0] = RAGDOLL_RELEASE_SUPPRESSION_FRAMES;
                    }
                } else if (landingSuppressionFramesLeft[0] > 0) {
                    landingSuppressionFramesLeft[0]--;
                    if (landingSuppressionFramesLeft[0] == 0) {
                        world.suppressAutoLanding = false;
                        awaitingSecondCollision[0] = true;
                    }
                } else if (awaitingSecondCollision[0] && !body.anchors.isEmpty()) {
                    // the next real collision, after actually falling away from
                    // the release point -- start the recover-to-standing countdown.
                    awaitingSecondCollision[0] = false;
                    secondCollisionTimerRunning[0] = true;
                    secondsSinceSecondCollision[0] = 0.0;
                } else if (secondCollisionTimerRunning[0]) {
                    secondsSinceSecondCollision[0] += 1.0 / 60.0;
                    if (secondsSinceSecondCollision[0] >= JUMP_RECOVER_DELAY_SECONDS) {
                        secondCollisionTimerRunning[0] = false;
                        jumpPendingStandRecovery[0] = true;
                        Body standing = loadPose(profile.standingPathFor(facingSign[0]));
                        targetPose[0] = standing;
                        Tip fixpointTip = body.tipByName.get(profile.fixpointTip);
                        poseMorpher.setTarget(standing, JUMP_RECOVERY_MORPH_SECONDS,
                                clearStandingSpot(standing, profile.fixpointTip, fixpointTip.position, world), fixpointTip);
                    }
                }
            }
            redraw(body, world);
            if (jumpCharging[0] && jumpIsKeyDriven[0]) {
                double fraction = Math.max(0.0, Math.min(1.0, jumpChargeElapsed[0] / JUMP_CHARGE_SECONDS));
                drawChargeMeter(body, fraction);
            }
        };
        // abandons every sequence in flight (walk, morph, jump, ragdoll) --
        // before the body gets rebuilt, since they hold on to its old tips.
        Runnable cancelSequences = () -> {
            walker.stop();
            walkPendingStop[0] = false;
            poseMorpher.cancel();
            jumpCharging[0] = false;
            jumpPendingLaunch[0] = false;
            jumpPendingChargeStart[0] = false;
            jumpKeyHeld[0] = false;
            awaitingCollision[0] = false;
            collisionTimerRunning[0] = false;
            landingSuppressionFramesLeft[0] = 0;
            awaitingSecondCollision[0] = false;
            secondCollisionTimerRunning[0] = false;
            jumpPendingStandRecovery[0] = false;
        };
        viewer.onReset = () -> {
            cancelSequences.run();
            resetBody(body, world);
        };

        // switches the playable figure and rebuilds it fresh at the starting
        // position -- also for the figure already playing, so picking it
        // again in the selector starts over. Shared by the selector on the
        // right and the 'h' key (which cycles), and keeps both in sync.
        Consumer<CharacterProfile> switchCharacter = next -> {
            cancelSequences.run();
            profile = next;
            currentPoseFile = null; // a loaded pose belongs to the old figure's skeleton
            facingSign[0] = -1.0;
            try {
                applySkin(body);
                AnimationClip[] clips = loadWalkClips();
                walkClips[0] = clips[0];
                walkClips[1] = clips[1];
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            viewer.setTitle("Stick Figure - " + profile.name);
            viewer.setSelectedCharacter(profile.name);
            resetBody(body, world);
        };
        List<String> characterNames = new ArrayList<>();
        for (CharacterProfile p : CharacterProfile.ALL) {
            characterNames.add(p.name);
        }
        viewer.setCharacterChoices(characterNames, profile.name);
        viewer.setTitle("Stick Figure - " + profile.name);
        viewer.onSelectCharacter = name -> switchCharacter.accept(CharacterProfile.byName(name));
        viewer.onToggleCharacter = () -> {
            int next = (CharacterProfile.ALL.indexOf(profile) + 1) % CharacterProfile.ALL.size();
            switchCharacter.accept(CharacterProfile.ALL.get(next));
        };

        // drag: grab whichever tip is closest to where the mouse went down, then
        // once the mouse comes back up, give that same tip a velocity kick in the
        // drag direction, scaled by how far it was dragged -- a "flick", not a
        // continuously-applied spring while dragging.
        Tip[] grabbedTip = new Tip[1];
        viewer.onDragStart = worldPos -> grabbedTip[0] = body.closestTip(worldPos);
        viewer.onDragEnd = (start, end) -> {
            if (grabbedTip[0] != null) {
                TupleD dragVector = end.sub(start);
                grabbedTip[0].velocity = grabbedTip[0].velocity.add(dragVector.times(DRAG_KICK_SCALE));
                grabbedTip[0] = null;
            }
        };

        // click (as opposed to a drag): toggle an Anchor at whatever's near
        // the click -- see Body.toggleAnchor for the remove-vs-add order.
        // Shift-click creates a position-only anchor (no angle lock). Redraws
        // immediately so the marker appears even while paused -- otherwise
        // nothing would show until the next Play/Step tick.
        viewer.onClick = (worldPos, shiftHeld) -> {
            body.toggleAnchor(worldPos, shiftHeld);
            redraw(body, world);
        };

        // right-drag: pick up whichever anchor is near where the mouse went
        // down, then drag it (and whatever it's pinning) around live --
        // clamped against any OTHER active anchor's reach (Body.clampAnchorDrag).
        // holdAngles() re-derives the DRAGGED anchor's own segments straight
        // from its locked angle first, since the position-only solve that
        // follows has no notion of angle (only length/coincidence) and would
        // otherwise leave any of its segments not independently pinned
        // elsewhere free to swing to a wildly different orientation from even
        // a tiny drag. That solve then only has to settle the REST of the
        // chain (e.g. a bent knee between a hip anchor and a foot anchor).
        // Every anchor's angle target is re-frozen afterward so nothing snaps
        // back the instant normal simulation (Play/Step) resumes.
        Anchor[] grabbedAnchor = new Anchor[1];
        viewer.onRightDragStart = worldPos -> grabbedAnchor[0] = body.grabAnchorNear(worldPos);
        viewer.onRightDrag = worldPos -> {
            if (grabbedAnchor[0] != null) {
                TupleD clamped = body.clampAnchorDrag(grabbedAnchor[0], worldPos);
                grabbedAnchor[0].moveTo(clamped);
                grabbedAnchor[0].holdAngles();
                grabbedAnchor[0].freezeFarTips();
                world.resolvePositions();
                grabbedAnchor[0].unfreezeFarTips();
                for (Anchor a : body.anchors) {
                    a.refreezeAngles();
                }
                redraw(body, world);
            }
        };

        // StorePose/LoadPose: full skeleton-config snapshots (Bones/Attachables/
        // PhysicalUpgrades, same schema as Skeletons.json) -- see Body.storePose/loadPose.
        viewer.onStorePose = file -> {
            try {
                body.storePose(file);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        };
        viewer.onLoadPose = file -> {
            try {
                body.loadPose(file);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            currentPoseFile = file;
            redraw(body, world);
        };

        // Load Target: parses a pose file into a separate, static reference
        // Body -- never stepped, just read by Morph for its angles/targets.
        viewer.onLoadTarget = file -> {
            Body t = new Body();
            try {
                t.loadPose(file);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            targetPose[0] = t;
        };

        // Morph: arms the morpher toward the loaded target, keeping the
        // fixpoint exactly where it currently is (reposturing in place, not
        // relocating). onStep (above) then drives it forward each tick while
        // active. Fixpoint is the profile's (e.g. the human's left foot) --
        // looked up by name each time rather than cached, since Reset/LoadPose
        // rebuild body.bone[] with fresh objects.
        viewer.onMorph = () -> {
            if (targetPose[0] != null) {
                Tip fixpointTip = body.tipByName.get(profile.fixpointTip);
                poseMorpher.setTarget(targetPose[0], viewer.getMorphTimeSeconds(),
                        fixpointTip.position, fixpointTip);
            }
        };

        // Jump: loads the charging pose (with its own anchors) at the
        // viewer's right border, then hands off to onStep above -- it plays
        // physics for JUMP_CHARGE_SECONDS, morphs to the flying pose over
        // JUMP_MORPH_SECONDS, then launches. Ignored while a jump/morph is
        // already in progress.
        viewer.onJump = () -> {
            if (jumpCharging[0] || jumpPendingLaunch[0] || jumpPendingChargeStart[0] || poseMorpher.isActive()) {
                return;
            }
            walker.stop();
            try {
                body.loadPose(new File(profile.chargingPathL));
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
            currentPoseFile = new File(profile.chargingPathL);
            body.bone[0].tips[0].position = new TupleD(JUMP_START_X, body.bone[0].tips[0].position.second);
            body.recomputeGeometry();

            jumpDirectionSign[0] = -1.0; // this button always launches left, as before
            facingSign[0] = -1.0;
            jumpIsKeyDriven[0] = false; // fixed hold duration, fixed speed/angle
            jumpKeyHeld[0] = false;
            jumpChargeElapsed[0] = 0.0;
            jumpCharging[0] = true;
            jumpPendingLaunch[0] = false;
            jumpPendingChargeStart[0] = false;
            awaitingCollision[0] = false;
            collisionTimerRunning[0] = false;
            landingSuppressionFramesLeft[0] = 0;
            awaitingSecondCollision[0] = false;
            secondCollisionTimerRunning[0] = false;
            jumpPendingStandRecovery[0] = false;
            world.suppressAutoLanding = false;

            redraw(body, world);
            viewer.startPlaying();
        };

        // keypress jump ('o' left / 'p' right, see Viewer's KeyListener):
        // unlike the JUMP button, this starts from wherever the figure
        // currently stands -- morphs in place to the charging pose first
        // (jumpPendingChargeStart), then onStep's own morph-completion
        // handling falls into the ordinary charge/fly/launch sequence, using
        // directionSign for which way the final launch kicks. Ignored while
        // any jump/morph/recovery sequence is already in progress.
        DoubleConsumer startKeyJump = directionSign -> {
            if (jumpCharging[0] || jumpPendingLaunch[0] || jumpPendingChargeStart[0] || poseMorpher.isActive()) {
                return;
            }
            walker.stop(); // jumping straight out of a walk: the charge morph starts from the current walk frame
            if (profile.sideView && directionSign != facingSign[0]) {
                for (Anchor a : new ArrayList<>(body.anchors)) {
                    body.removeAnchor(a.tipsSnapshot()[0].name);
                }
                turnAround(body, world);
            }
            Body charging = loadPose(profile.chargingPathFor(directionSign));

            jumpDirectionSign[0] = directionSign;
            facingSign[0] = directionSign;
            jumpIsKeyDriven[0] = true;
            jumpKeyHeld[0] = true; // released via viewer.onJumpKeyReleased below
            targetPose[0] = charging;
            jumpPendingChargeStart[0] = true;
            awaitingCollision[0] = false;
            collisionTimerRunning[0] = false;
            landingSuppressionFramesLeft[0] = 0;
            awaitingSecondCollision[0] = false;
            secondCollisionTimerRunning[0] = false;
            jumpPendingStandRecovery[0] = false;
            world.suppressAutoLanding = false;

            Tip fixpointTip = body.tipByName.get(profile.fixpointTip);
            poseMorpher.setTarget(charging, JUMP_MORPH_SECONDS, fixpointTip.position, fixpointTip);
            viewer.startPlaying();
        };
        viewer.onJumpLeft = () -> startKeyJump.accept(-1.0);
        viewer.onJumpRight = () -> startKeyJump.accept(1.0);

        // ends the current keypress jump's hold (see jumpKeyHeld above) --
        // a no-op if nothing is currently charging (e.g. the key came up
        // after a jump/launch already finished, or was never the one that
        // started a charge in the first place).
        viewer.onJumpKeyReleased = () -> jumpKeyHeld[0] = false;

        // keyboard walking ('u' left / 'i' right, see Viewer's KeyListener):
        // starts from wherever the figure currently stands, blending into the
        // clip (ClipPlayer.start). Only from idle -- ignored while walking
        // already (which also swallows the OS's key auto-repeat) or while any
        // jump/morph/ragdoll sequence is in progress. Anchors are dropped
        // first: the walk plants its own feet, and stale ground pins would
        // yank the figure back once physics resumes.
        DoubleConsumer startWalk = directionSign -> {
            if (walker.isActive() || poseMorpher.isActive() || jumpCharging[0] || jumpPendingLaunch[0]
                    || jumpPendingChargeStart[0] || awaitingCollision[0] || collisionTimerRunning[0]
                    || landingSuppressionFramesLeft[0] > 0 || awaitingSecondCollision[0]
                    || secondCollisionTimerRunning[0] || jumpPendingStandRecovery[0]) {
                return;
            }
            // ...and only with a foot actually on the ground -- not, e.g.,
            // while tumbling through the air after being knocked away.
            boolean grounded = false;
            for (String foot : profile.feetTips) {
                grounded |= hasGroundBelow(world, body.tipByName.get(foot).position);
            }
            if (!grounded) {
                return;
            }
            for (Anchor a : new ArrayList<>(body.anchors)) {
                body.removeAnchor(a.tipsSnapshot()[0].name);
            }
            if (profile.sideView && directionSign != facingSign[0]) {
                turnAround(body, world);
            }
            facingSign[0] = directionSign;
            AnimationClip clip = directionSign < 0.0 ? walkClips[0] : walkClips[1];
            walker.start(clip, body, ClipPlayer.startTimeFor(clip, body));
            viewer.startPlaying();
        };
        viewer.onWalkLeft = () -> startWalk.accept(-1.0);
        viewer.onWalkRight = () -> startWalk.accept(1.0);
        viewer.onWalkKeyReleased = stopWalk;
    }

    // -------------------------------------------------------------------------
    // mirrors `pose` horizontally around its hip, in place -- same rule as
    // the _L -> _R pose files (absolute bone angle theta -> 180 - theta).
    // Geometry only: meant for a morph TARGET, whose motor targets the
    // morpher derives from the geometry anyway.
    private static void mirrorPose(Body pose) {
        for (Bone b : pose.bone) {
            b.angleDeg = 180.0 - Math.toDegrees(b.angle());
        }
        pose.propagatePositions(pose.bone[0].tips[0]);
    }

    // -------------------------------------------------------------------------
    // a side-on figure turning to face the other way: flipped horizontally in
    // place -- mirrored like a _L -> _R pose, then shifted back so it stays
    // centered where it stood, the classic 2D-sprite turn. A morph instead
    // would swing every bone the short way round, spinning the body through
    // vertical. On uneven ground the mirrored feet land on the wrong levels,
    // so it's then moved up or down until they stand on the ground again
    // rather than sinking into it (at least one touching, none below). Motor
    // targets follow the new geometry (a mirrored relative angle is just
    // negated), so physics holds it as it is.
    private static void turnAround(Body body, World world) {
        double centerBefore = horizontalCenter(body);
        mirrorPose(body);
        double shift = centerBefore - horizontalCenter(body);
        double lift = Double.NEGATIVE_INFINITY;
        for (String foot : profile.feetTips) {
            TupleD p = body.tipByName.get(foot).position;
            double g = world.groundHeight(p.first + shift, p.second + ClipPlayer.MAX_STEP_UP, p.second - ClipPlayer.MAX_STEP_DOWN);
            if (!Double.isNaN(g)) {
                lift = Math.max(lift, g - p.second);
            }
        }
        if (lift == Double.NEGATIVE_INFINITY) {
            lift = 0.0;
        }
        for (Tip tip : body.tipByName.values()) {
            tip.position = new TupleD(tip.position.first + shift, tip.position.second + lift);
            tip.velocity = new TupleD(0.0, 0.0);
        }
        for (Motor m : body.motors) {
            m.targetAngleDeg = Math.toDegrees(Motor.relativeAngleRad(m.joint));
        }
    }

    // -------------------------------------------------------------------------
    private static double horizontalCenter(Body body) {
        double minX = Double.POSITIVE_INFINITY;
        double maxX = Double.NEGATIVE_INFINITY;
        for (Tip tip : body.tipByName.values()) {
            minX = Math.min(minX, tip.position.first);
            maxX = Math.max(maxX, tip.position.first);
        }
        return 0.5 * (minX + maxX);
    }

    // -------------------------------------------------------------------------
    // where to put a standing-up morph's pivot foot so the standing pose ends
    // up clear of the rocks and not below the floor: right where the foot is
    // if that fits, else the nearest spot sideways that does (up to
    // CLEAR_SPOT_SEARCH either way), each time seated on the ground under the
    // foot. E.g. after landing against a rock wall, the horse's head would
    // otherwise stand up right into it -- and get thrown out by the contact.
    private static TupleD clearStandingSpot(Body standing, String pivotTip, TupleD pivot, World world) {
        TupleD pivotInPose = standing.tipByName.get(pivotTip).position;
        int steps = (int) Math.round(CLEAR_SPOT_SEARCH / CLEAR_SPOT_STEP);
        for (int i = 0; i <= 2 * steps; i++) {
            double dx = ((i + 1) / 2) * CLEAR_SPOT_STEP * (i % 2 == 1 ? 1.0 : -1.0); // 0, +d, -d, +2d, ...
            double x = pivot.first + dx;
            double ground = world.groundHeight(x, pivot.second + ClipPlayer.MAX_STEP_UP, pivot.second - 2.0);
            TupleD candidate = new TupleD(x, Double.isNaN(ground) ? pivot.second : ground);
            boolean clear = true;
            for (Tip t : standing.tipByName.values()) {
                // nudged up a hair: a foot resting exactly on a rock counts as clear
                TupleD p = candidate.add(t.position.sub(pivotInPose)).add(new TupleD(0.0, 0.01));
                if (p.second < 0.0 || world.insideObstacle(p)) {
                    clear = false;
                    break;
                }
            }
            if (clear) {
                return candidate;
            }
        }
        return pivot;
    }

    // -------------------------------------------------------------------------
    // true if the ground under every foot is at one level (within
    // LEVEL_GROUND_TOLERANCE) -- each foot's ground found by looking down
    // from it, so a foot lifted mid-step still counts by what it's over.
    private static boolean groundIsLevelUnder(World world, Body body) {
        double lowest = Double.POSITIVE_INFINITY;
        double highest = Double.NEGATIVE_INFINITY;
        for (String foot : profile.feetTips) {
            TupleD p = body.tipByName.get(foot).position;
            double g = world.groundHeight(p.first, p.second + WALK_GROUND_TOLERANCE, p.second - 2.0 * ClipPlayer.MAX_STEP_DOWN);
            if (Double.isNaN(g)) {
                return false;
            }
            lowest = Math.min(lowest, g);
            highest = Math.max(highest, g);
        }
        return highest - lowest <= LEVEL_GROUND_TOLERANCE;
    }

    // -------------------------------------------------------------------------
    // true if `footPos` stands on something: the floor (y=0), or a rock
    // surface within WALK_GROUND_TOLERANCE below it.
    private static boolean hasGroundBelow(World world, TupleD footPos) {
        return !Double.isNaN(world.groundHeight(footPos.first,
                footPos.second + WALK_GROUND_TOLERANCE, footPos.second - WALK_GROUND_TOLERANCE));
    }

    // -------------------------------------------------------------------------
    // a horizontal bar below the figure (its lowest tip, e.g. a foot -- not a
    // fixed world height, so it still sits right under the figure even
    // standing on a raised rock), centered under the figure: a light-gray
    // full-width track plus an orange fill growing left-to-right with the
    // charge fraction (0..1), giving live feedback on how long 'o'/'p' has
    // been held (see JUMP_LAUNCH_SPEED_MIN/MAX and the angle equivalents,
    // which the fraction ultimately maps to at launch time).
    private static void drawChargeMeter(Body body, double fraction) {
        double lowestY = Double.POSITIVE_INFINITY;
        double minX = Double.POSITIVE_INFINITY;
        double maxX = Double.NEGATIVE_INFINITY;
        for (Bone b : body.bone) {
            for (Tip t : b.tips) {
                lowestY = Math.min(lowestY, t.position.second);
                minX = Math.min(minX, t.position.first);
                maxX = Math.max(maxX, t.position.first);
            }
        }
        double centerX = 0.5 * (minX + maxX);
        double meterY = lowestY - CHARGE_METER_GAP_BELOW_FIGURE;

        viewer.drawRect(new TupleD(centerX, meterY), CHARGE_METER_WIDTH, CHARGE_METER_HEIGHT,
                new Color(200, 200, 200));
        double fillWidth = CHARGE_METER_WIDTH * fraction;
        double fillCenterX = centerX - CHARGE_METER_WIDTH / 2.0 + fillWidth / 2.0;
        viewer.drawRect(new TupleD(fillCenterX, meterY), fillWidth, CHARGE_METER_HEIGHT, Color.ORANGE);
    }

    // -------------------------------------------------------------------------
    // a pose file as a separate, never-stepped Body -- e.g. a morph target.
    private static Body loadPose(String path) {
        Body pose = new Body();
        try {
            pose.loadPose(new File(path));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        return pose;
    }

    // -------------------------------------------------------------------------
    // {walk left, walk right} for the current profile -- right is left's mirror.
    private static AnimationClip[] loadWalkClips() throws IOException {
        AnimationClip left = AnimationClip.load(profile.walkClipPathL);
        return new AnimationClip[]{left, left.mirrored()};
    }

    // -------------------------------------------------------------------------
    // the current profile's cut-out skin (from editor.SkinEditor), if it has
    // one saved -- bones without a cut (or no skin at all) keep their default
    // ellipse.
    private static void applySkin(Body body) throws IOException {
        body.skin = null;
        if (profile.skinPath != null && new File(profile.skinPath).isFile()) {
            body.skin = Skin.load(new File(profile.skinPath));
        }
    }

    // rebuilds `body` fresh from the JSON (fresh Tips means velocity/prevPosition
    // reset too, not just position), then puts it back into either the loaded
    // pose (if LoadPose has been used) or the default starting pose -- shared
    // by startup and the Reset button so they can never drift apart.
    private static void resetBody(Body body, World world) {
        world.suppressAutoLanding = false;
        try {
            body.buildFromConfig(profile.initialPath);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }

        if (currentPoseFile != null) {
            try {
                body.loadPose(currentPoseFile);
            } catch (IOException e) {
                throw new RuntimeException(e);
            }
        } else {
            // reposition hip to [0,1]
            body.bone[0].tips[0].position = new TupleD(0, 1.2);
            body.recomputeGeometry();
        }

        viewer.drawFloor();
        redraw(body, world);
    }

    // -------------------------------------------------------------------------
    // re-centers the camera on the profile's camera tip, e.g. the human's
    // neck (so the viewer scrolls to follow the figure rather than staying
    // fixed on the world origin), then redraws everything -- shared by every
    // site that changes the pose/anchors/obstacles and needs the screen to
    // reflect it. A no-op camera move if that tip isn't found.
    private static void redraw(Body body, World world) {
        Tip focusTip = body.tipByName.get(profile.cameraTip);
        if (focusTip != null) {
            viewer.setCameraFocus(focusTip.position);
        }
        viewer.clear();
        for (Polygon obstacle : world.obstacles) {
            obstacle.display();
        }
        body.draw();
    }

}
